services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: always
    networks:
      - app_network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    restart: always
    networks:
      - app_network

  nginx:
    build:
      context: ./requirements/nginx
      args:
        LOGIN: ${LOGIN}
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress
