version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    restart: always
    networks:
      - app_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    env_file: .env
    restart: always
    networks:
      - app_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/data/wordpress
